/* tslint:disable */
/* eslint-disable */
/**
 * Piped API
 * This is an API specification for Piped API instances.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kavin@kavin.rocks
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StreamItem } from './stream-item';
/**
 * 
 * @export
 * @interface ChannelInfo
 */
export interface ChannelInfo {
    /**
     * The URL of the channel's avatar.
     * @type {string}
     * @memberof ChannelInfo
     */
    avatarUrl?: string;
    /**
     * The URL of the channel's banner.
     * @type {string}
     * @memberof ChannelInfo
     */
    bannerUrl?: string;
    /**
     * The channel's description.
     * @type {string}
     * @memberof ChannelInfo
     */
    description?: string;
    /**
     * The ID of the channel.
     * @type {string}
     * @memberof ChannelInfo
     */
    id?: string;
    /**
     * The name of the channel.
     * @type {string}
     * @memberof ChannelInfo
     */
    name?: string;
    /**
     * The parameter used to get the next page of related videos.
     * @type {string}
     * @memberof ChannelInfo
     */
    nextpage?: string;
    /**
     * 
     * @type {Array<StreamItem>}
     * @memberof ChannelInfo
     */
    relatedStreams?: Array<StreamItem>;
    /**
     * The number of subscribers the channel has.
     * @type {number}
     * @memberof ChannelInfo
     */
    subscriberCount?: number;
    /**
     * Whether the channel is verified.
     * @type {boolean}
     * @memberof ChannelInfo
     */
    verified?: boolean;
}
