/* tslint:disable */
/* eslint-disable */
/**
 * Piped API
 * This is an API specification for Piped API instances.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kavin@kavin.rocks
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ChannelItem
 */
export interface ChannelItem {
    /**
     * The description of the channel.
     * @type {string}
     * @memberof ChannelItem
     */
    description?: string;
    /**
     * The name of the channel.
     * @type {string}
     * @memberof ChannelItem
     */
    name?: string;
    /**
     * The number of subscribers the channel has.
     * @type {number}
     * @memberof ChannelItem
     */
    subscribers?: number;
    /**
     * The thumbnail of the channel.
     * @type {string}
     * @memberof ChannelItem
     */
    thumbnail?: string;
    /**
     * The relative URL of the channel.
     * @type {string}
     * @memberof ChannelItem
     */
    url?: string;
    /**
     * Whether the channel is verified.
     * @type {boolean}
     * @memberof ChannelItem
     */
    verified?: boolean;
    /**
     * The number of videos the channel has.
     * @type {number}
     * @memberof ChannelItem
     */
    videos?: number;
}
