/* tslint:disable */
/* eslint-disable */
/**
 * Piped API
 * This is an API specification for Piped API instances.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kavin@kavin.rocks
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comment } from './comment';
/**
 * 
 * @export
 * @interface CommentsPage
 */
export interface CommentsPage {
    /**
     * 
     * @type {Array<Comment>}
     * @memberof CommentsPage
     */
    comments?: Array<Comment>;
    /**
     * The parameter used to get the next page of comments.
     * @type {string}
     * @memberof CommentsPage
     */
    nextpage?: string | null;
    /**
     * Whether or not comments are disabled on the video.
     * @type {boolean}
     * @memberof CommentsPage
     */
    disabled?: boolean;
}
