/* tslint:disable */
/* eslint-disable */
/**
 * Piped API
 * This is an API specification for Piped API instances.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kavin@kavin.rocks
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * When a server-side exception takes place.
 * @export
 * @interface ExceptionError
 */
export interface ExceptionError {
    /**
     * The stacktrace provided by the server.
     * @type {string}
     * @memberof ExceptionError
     */
    error: string;
    /**
     * The error message from the stacktrace.
     * @type {string}
     * @memberof ExceptionError
     */
    message: string;
}
