/* tslint:disable */
/* eslint-disable */
/**
 * Piped API
 * This is an API specification for Piped API instances.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kavin@kavin.rocks
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum SearchFilter {
    All = 'all',
    Videos = 'videos',
    Channels = 'channels',
    Playlists = 'playlists',
    MusicSongs = 'music_songs',
    MusicVideos = 'music_videos',
    MusicAlbums = 'music_albums',
    MusicPlaylists = 'music_playlists'
}

