/* tslint:disable */
/* eslint-disable */
/**
 * Piped API
 * This is an API specification for Piped API instances.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kavin@kavin.rocks
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SearchItem } from './search-item';
/**
 * 
 * @export
 * @interface SearchPage
 */
export interface SearchPage {
    /**
     * Whether the search query was corrected.
     * @type {boolean}
     * @memberof SearchPage
     */
    corrected?: boolean;
    /**
     * 
     * @type {Array<SearchItem>}
     * @memberof SearchPage
     */
    items?: Array<SearchItem>;
    /**
     * The parameter used to get the next page of this page.
     * @type {string}
     * @memberof SearchPage
     */
    nextpage?: string | null;
    /**
     * The suggested search query.
     * @type {string}
     * @memberof SearchPage
     */
    suggestion?: string | null;
}
