/* tslint:disable */
/* eslint-disable */
/**
 * Piped API
 * This is an API specification for Piped API instances.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kavin@kavin.rocks
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StreamItem } from './stream-item';
/**
 * 
 * @export
 * @interface StreamsPage
 */
export interface StreamsPage {
    /**
     * 
     * @type {Array<StreamItem>}
     * @memberof StreamsPage
     */
    relatedStreams?: Array<StreamItem>;
    /**
     * The parameter used to get the next page of this page.
     * @type {string}
     * @memberof StreamsPage
     */
    nextpage?: string | null;
}
