/* tslint:disable */
/* eslint-disable */
/**
 * Piped API
 * This is an API specification for Piped API instances.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kavin@kavin.rocks
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Stream } from './stream';
import { StreamItem } from './stream-item';
import { Subtitle } from './subtitle';
/**
 * 
 * @export
 * @interface VideoInfo
 */
export interface VideoInfo {
    /**
     * 
     * @type {Array<Stream>}
     * @memberof VideoInfo
     */
    audioStreams?: Array<Stream>;
    /**
     * 
     * @type {Array<Stream>}
     * @memberof VideoInfo
     */
    videoStreams?: Array<Stream>;
    /**
     * The video's description.
     * @type {string}
     * @memberof VideoInfo
     */
    description?: string;
    /**
     * The number of dislikes the video has.
     * @type {number}
     * @memberof VideoInfo
     */
    dislikes?: number;
    /**
     * The video's duration in seconds.
     * @type {number}
     * @memberof VideoInfo
     */
    duration?: number;
    /**
     * The stream of the video in a HLS manifest.
     * @type {string}
     * @memberof VideoInfo
     */
    hls?: string;
    /**
     * The LBRY ID of the video.
     * @type {string}
     * @memberof VideoInfo
     */
    lbryId?: string;
    /**
     * The number of likes the video has.
     * @type {number}
     * @memberof VideoInfo
     */
    likes?: number;
    /**
     * Whether the video is a livestream.
     * @type {boolean}
     * @memberof VideoInfo
     */
    livestream?: boolean;
    /**
     * The base URL of the backend instance's proxy.
     * @type {string}
     * @memberof VideoInfo
     */
    proxyUrl?: string;
    /**
     * 
     * @type {Array<Subtitle>}
     * @memberof VideoInfo
     */
    subtitles?: Array<Subtitle>;
    /**
     * The URL of the DASH manifest.
     * @type {string}
     * @memberof VideoInfo
     */
    dash?: string;
    /**
     * The URL of the video's thumbnail.
     * @type {string}
     * @memberof VideoInfo
     */
    thumbnailUrl?: string;
    /**
     * The video's title.
     * @type {string}
     * @memberof VideoInfo
     */
    title?: string;
    /**
     * The date the video was uploaded.
     * @type {string}
     * @memberof VideoInfo
     */
    uploadDate?: string;
    /**
     * The video's uploader.
     * @type {string}
     * @memberof VideoInfo
     */
    uploader?: string;
    /**
     * The URL of the video's uploader's avatar.
     * @type {string}
     * @memberof VideoInfo
     */
    uploaderAvatar?: string;
    /**
     * The relative URL of the video's uploader.
     * @type {string}
     * @memberof VideoInfo
     */
    uploaderUrl?: string;
    /**
     * Whether the video's uploader is verified.
     * @type {boolean}
     * @memberof VideoInfo
     */
    uploaderVerified?: boolean;
    /**
     * The number of views the video has.
     * @type {number}
     * @memberof VideoInfo
     */
    views?: number;
    /**
     * 
     * @type {Array<StreamItem>}
     * @memberof VideoInfo
     */
    relatedStreams?: Array<StreamItem>;
}
